server:
  port: 8080

spring:
  application:
    name: clother

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  data:
    redis:
      host: localhost
      port: 6379

# ===== 커스텀 애플리케이션 설정 =====
app:
  mail:
    auth-code-expiration-millis: 1800000   # 30분
  redis:
    duration-seconds: 600                  # 10분
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: 3600000       # 1시간
    refresh-token-expiration: 604800000    # 7일

cloud:
  aws:
    s3:
      bucket: min-clother
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ${AWS_ACCESS_KEY_ID:}
      secretKey: ${AWS_SECRET_ACCESS_KEY:}

logging:
  level:
    com.min.clother.post: DEBUG
